### ISSUE TITLE
Feedback end call appears way too often

### ISSUE THREAD

**Issue by dillfrescott** [vector-im/element-call#1096]
#### What would you like to do?

I'd like for the feedback screen to either have an option to stop appearing or for it to only come up maybe once a day.

### Have you considered any alternatives?

No

### Additional context

No

**Comment by jakewb-b** [comment]
Hey @dillfrescott. Thanks for the feedback. It's important to us to obtain as much feedback as possible, and ideally on *all* calls, not just on a selection of calls (e.g. one per day per user) so that we can accurately get a sense of our users' subjective impression of how good the call was, and hopefully make improvements, as well as our more objective/quantitative metrics. 

My question would be why you feel the feedback screen appears 'too often' and what problem this creates for you? The feedback request is simply an addition to the 'Your call has ended' screen that has always appeared at the end of every call. There is no obligation to provide feedback so, if you don't want to, you can simply close the tab as you presumably would have with the 'your call has ended' screen previously.

**Comment by dillfrescott** [comment]
Thank you for your response. Basically the way I see it is that having it appear every time the call is ended seems just too frequent.

I suppose that's a matter of opinion, but just like discord has the option to never show the feedback box again, I think the more choices and/or abilities the user is able to have, the better.

**Comment by jakewb-b** [comment]
Thanks - that's a fair point, although for the time being I'm going to close this as something we're not looking to change. My view is that we've simply added an optional form to an existing screen, while leaving in place both of the existing ways to leave that screen (closing the tab, or clicking on the link to go home). Given that, I don't feel there's a need to provide an option for users *not* to see that form, and in fact doing so just adds another complication that might in itself be undesirable. 

As we get the product out of beta, get more user feedback, and have time to further consider what options and customisations we want to provide, we could certainly look at this again though.

**Comment by dillfrescott** [comment]
Ok sounds good to me!
