### ISSUE TITLE
Fix simulcast screen sharing

### ISSUE THREAD

**Issue by fkwp** [vector-im/element-call#1189]
Screen-sharing does not work in Chrome.

**Comment by daniel-abramov** [comment]
**UPD.** Chrome does not work with simulcast layers specified for screen sharing (see https://github.com/vector-im/element-call/pull/1207 for more info).

https://github.com/vector-im/element-call/pull/1207 fixes screen-sharing in Chrome and makes Chrome and Firefox use 30 fps screen-sharing when possible.

It seems like it **might be** a bug in the SDK (more investigations are required). It **could be** that screen-sharing simulcast presets are only required for **spatial layers** and that the temporal layers are calculated automatically when possible based on the encoding configuration (where the max encoding specifies 30 fps in https://github.com/vector-im/element-call/pull/1207).

More tests are required. If we note that the FPS varies depending on bandwidth, then this problem is solved (meaning that we get temporal layers "for free" [without configuration] and only need to specify screen sharing layers if we need spatial layers).

**Comment by dbkr** [comment]
Screensharing works again as of 1207 above, so closing this as this is just about it working at all. We can track enabling simulcast separately.
