### ISSUE TITLE
Update m.call event with latest SFU Service URL in case of failed JWT request

### ISSUE THREAD

**Issue by fkwp** [vector-im/element-call#1190]
There are cases where the SFU Service URL in the m.call event is outdated over time (e.g., in a very long running video session like in the SPA or video rooms).

In such cases we need to update the SFU Service URL in the m.call event as follows:
- If the SFU Service URL from the `m.call` event does not respond or returns an error code
  - If the (latest) SFU Service URL (provided from config.json) differs from that one in the `m.call` we update the state event with the new one + check the new Service URL prior to updating the `m.call` event

**Comment by daniel-abramov** [comment]
I was just checking this part of the code since I fixed some merge conflicts that were related to the issue.

Correct me if I'm wrong, but currently it looks like there are no cases where the SFU service URL can get outdated even in longer calls since we never change one? Also it feels like changing the URL in the `m.call` may have some adverse effects, i.e. the fact that the URL from the `m.call` event does not work or invalid does not necessarily mean that the URL is bad, a user could have experienced a network problem or something similar, so updating the `m.call` event may have some unintended effects - imagine a large conference of 100 users where 20 users had problem to contact the URL for some reason and then each starts updating that single `m.call` event with whatever URL is present in their config.

I think the plausible workaround that we can implement for the scenario if the URL is not available (for one reason or another) is to let the user first try the URLs specified in the event and only if they fail, use the URLs that are configured on their side **without** modifying the `m.call` event. That way we're not running into a risk of multiple users modifying an event that [perhaps] is not really meant to be modified by those ones who are not the creators of the call (after all, the creator of the call might have shared the preferred list of SFU service URLs).

**Comment by dbkr** [comment]
The problem here is that the call event in an element call room or a video room will remain current for as long as that room is used, ie. maybe several years. A homeserver/SFU might entirely disappear in that timeframe, so we're after a way to make the call choose a new SFU without having to just move to another room. There are certainly risks with clients updating the SFU unnecessarily when they have network blips, the hope here is that most of the time their configured URL will be the same so there would be no reason to update it (and/or it will require that the check to the current URL fails and the check to their new URL succeeds, which is still possible but less likely).

Using our configured SFU and not updating the event will just lead to an unrecoverable split-brain situation if the SFU in the call event goes away, since clients will just use their own SFUs rather than agree on one, though.

**Comment by daniel-abramov** [comment]
> The problem here is that the call event in an element call room or a video room will remain current for as long as that room is used, ie. maybe several years. A homeserver/SFU might entirely disappear in that timeframe, so we're after a way to make the call choose a new SFU without having to just move to another room.

But the participants probably won't want to join a call that was created years ago? - I.e. in my understanding if 5 users had a call X 2 days ago, then if they want to start a new call several days after, they start a new call instead of trying to use the old one, or is my understanding incorrect? (if it isn't, then I wonder how are we going to move the placeholder event in the timeline to ensure that when people start the call each day, the call even the placeholder is placed in the correct position in the timeline)

> Using our configured SFU and not updating the event will just lead to an unrecoverable split-brain situation if the SFU in the call event goes away, since clients will just use their own SFUs rather than agree on one, though.

I get your point that ideally, the clients must connect to the same list of the SFUs (or SFU provider/jwt services) that are listed in the `m.call` event, because if everyone starts joining the SFU provider/jwt service that they have locally configured, then there is no guarantee they connect to the same SFU (unless cascading is implemented). So I understand your point, however, what I can't quite understand is how letting each participant update the `m.call` event ensures that they end up being connected to the same SFU (compared to the approach where they do not update the `m.call` event). 

If `N` concurrent participants update the `m.call` event based on a certain condition, then the problem becomes mathematically identical to the problem of `N` concurrent threads updating a variable, i.e. requires some synchronization primitive to ensure that the race does not happen.

**Comment by dbkr** [comment]
We never recreate the call in the element call SPA or a video room, the same call event just stays around for the lifetime of the room, so yep, users re-joining a call from days ago is actually the most common scenario we have currently. There's no timeline in these scenarios.

Ideally the synchronisation is provided by matrix's state resolution: if multiple clients do update the state event, the result should be eventually consistent, although in practice this doesn't work as well as it might.

**Comment by daniel-abramov** [comment]
> We never recreate the call in the element call SPA or a video room, the same call event just stays around for the lifetime of the room, so yep, users re-joining a call from days ago is actually the most common scenario we have currently. There's no timeline in these scenarios.

Ah, I see, it's for the SPA and video room scenario only, right? - Thanks for the explanation. Do you see a safe way to ensure that all participants connect to the same SFU? - Doing so via cascading would be the ideal solution.

> Ideally the synchronisation is provided by matrix's state resolution: if multiple clients do update the state event, the result should be eventually consistent

Yeah, but we need to ensure that **the state of each client** is then synchronized with the eventually consistent state of the state event, i.e. it means that whenever the state even is changed, all clients must get a notification and react accordingly - if they see that the URL of the SFU is different in the event, they must reconnect to the SFU. However, if they can't connect to the newly advertised SFU for some reason, it will, in turn, lead to them updating the event (if the solution suggested in the description is implemented), meaning that the change of the event would entail other clients starting reconnecting again (if the URL is different from what they have). There should be some condition to avoid an endless loop of updates (otherwise one client can break the conferencing experience for everyone participating in a call).

It feels like the only way to solve it elegantly is to either have a list of the SFUs that is e.g. set for the given room and cannot be updated by users (this way we have one source of truth for a given room that can't be modified by all users), or, perhaps, designing something based on the `m.call.member` event, where participants would specify preferred and active SFUs or something like this (AFAICR we might have discussed it in MSC3898).

**Comment by dbkr** [comment]
Yep, unfortunately without cascading we're in a situation where we need to make sure everyone agrees on the same URL. Indeed, we would need to leave the call & join a different SFU if it changed, so it sort of sucks. I don't love the idea but I can't really think of anything better, at least without designing something very complex and that feels like effort better spent on getting towards cascading.

**Comment by daniel-abramov** [comment]
Ok, I see. But how do we define the criteria for clients to stop updating the event? (i.e. how do we ensure that they won't continue to edit an event forever given the scenario I described in the previous comment?) And do we then observe the state of the state event to ensure we reconnect each time the state event changes?
