### ISSUE TITLE
No AEC on Firefox?

### ISSUE THREAD

**Issue by dbkr** [vector-im/element-call#1437]
### Steps to reproduce

We have observed that some users are causing echo because the browser does not appear to be doing AEC. The common denominator seems to be Firefox: switching to Chrome fixes the problem.

Is it possible AEC doesn't work on Firefox with e2ee enabled?

### Will you send logs?

No

**Comment by toger5** [comment]
## Findigs:
We tested and figured that the AEC starts when pressing on the settings button. This was very reproducable (we treid abut 5 times: reloading page - rejoining call - talking for 1min - pressing setting while the other participant was counting - the echo started exactly when pressing the button

@robintown IIRC we need to start a track when opening the setting so that `enumerateDevices` work. Could we try disabling this and see if that fixes the issue?
If so maybe it is enought to check if `enumerateDevices` works and ony start a track if it doesnt?

### second experiment
The issue is also reprodcuable like this:
Reload page - inside the lobby press the settings button - close the settings - join the call - echo is present for the other participants.

**Comment by toger5** [comment]
We will work around this by trying not to request a stream on startup.
`useMediaDeviceNames(devices);`
