### ISSUE TITLE
Spotlight layout is still jumpy and erratic

### ISSUE THREAD

**Issue by robintown** [vector-im/element-call#2219]
When people are talking and they're not a screensharer, they can end up glitching up and down rapidly in the spotlight right-hand column or swapping out of the main spotlight area really quickly

**Comment by dreamflasher** [comment]
Still unusable currently :(

**Comment by toger5** [comment]
There is a concrete approach how this issue is tackled:
 - The root cause for this is known and understood.
 - A overall refactor of the spotlight view is in the making. It is designed so there shouldn't be any erratic layout changes
 - It is not worthit to spend time to fix the old implementation (doing so would postpone the transition to the new implementation)
 
I hope this summary gives an overview what is going on that makes sense to anyone beeing annoyed by the jumpy spotlight view.

**Comment by robintown** [comment]
https://github.com/element-hq/element-call/pull/2382
