### ISSUE TITLE
Short / Readable invite URLs

### ISSUE THREAD

**Issue by exercismnow** [vector-im/element-call#2423]
#### What would you like to do?
When generating an invite link, add the option to shorten the link to something pretty and short.
e.g.
https://call.element.io/room/#/awefawefawef?roomId=!UlbJWGCfEEhWjOdXUg:call.ems.host&password=qn2KvL1ukdS0VTU4u3jiSA -> https://call.element.io/awefawefawef

#### Why would you like to do it?
I love that Element Call supports E2EE calls, and secures the calls via Matrix rooms and passwords (if I understand correctly)

However, Element Call links used to be much easier to share with friends.

Let's say you and your friend want to video chat, but they're not in a position to copy and paste a long link into their browser.

If we have short/pretty links, you could read the link out to them, and they could join without an issue.

#### How would you like to achieve it?
I'm not sure if it's possible/secure to use the same sort of link shortening method that other services like bit.ly do as a built-in part of Element Call.

### Additional context

Short/pretty links look more professional, and less unwieldy, in group chats. Having this feature also might increase Element Call's prestige.

**Comment by robintown** [comment]
We do want to switch to an approach where we're not encoding the password in the URL, but we still always will need some kind of token in the URL to at least authorize the person joining the call. Link shorteners are also not a good option for us, because then you're giving away the call's secrets to an external service.

Closing this as not planned, because there doesn't appear to be any way to remove "tokens" from the URL without compromizing on our other goals for the product.

The only optional piece which could be shortened is the human-readable name, though we made a product decision that our URLs are going to be long no matter what, so it's worth keeping it in there.
