### ISSUE TITLE
Broken base64 encoding for URL password parameter (shared secret) for SPA calls

### ISSUE THREAD

**Issue by fkwp** [vector-im/element-call#2429]

**Comment by robintown** [comment]
Figured out what's happening: [when converting to URL-safe base64](https://github.com/matrix-org/matrix-js-sdk/blob/c55289ec6583d71c309971fa5747b13c5b84d3ee/src/base64.ts#L62) we're calling `String.replace` instead of `String.replaceAll`, which replaces only the first instance of `+` or `/` in the key.
