### ISSUE TITLE
Screen sharing audio support on Firefox

### ISSUE THREAD

**Issue by ElTioRata** [vector-im/element-call#2497]
Related to #2398

This feature is only supported on Chrome as of now.

**Comment by fkwp** [comment]
as mentioned in https://github.com/element-hq/element-call/issues/2398 that is not possible with Firefox at the current point in time due to missing [Audio capture support](https://developer.mozilla.org/en-US/docs/Web/API/Screen_Capture_API/Using_Screen_Capture) in Firefox for getDisplayMedia which is the basis of screen sharing.

https://developer.mozilla.org/en-US/docs/Web/API/MediaDevices/getDisplayMedia#browser_compatibility
