### ISSUE TITLE
Element Call should start with Microphone in unmuted state on mobile

### ISSUE THREAD

**Issue by rajil** [vector-im/element-call#2714]
### Steps to reproduce

1. Where are you starting? What can you see?
Make a call using Element Call

#### What did you expect?
Ability to start conversing with the callee

#### What happened instead?
Microphone is disabled and needs to be enabled each time.

### Will you send logs?

No

**Comment by fkwp** [comment]
is this about using Element Call as widget or just the regular standalone SPA mode?

**Comment by rajil** [comment]
As a widget in EX.

**Comment by fkwp** [comment]
With https://github.com/element-hq/element-call/pull/2687 you can configure audio and video mute state to your needs for the lobby view. However, the lobby view is not presented in EX widget mode. Since Matrix is having a privacy preserving first mindset we initially chose to started muted in general. This is currently in discussion. We don't have yet an ETA. Will close the issue for now.
