### ISSUE TITLE
Element Call link not opened by Element X on recent Android device

### ISSUE THREAD

**Issue by bmarty** [vector-im/element-call#2806]
### Steps to reproduce

1. Try to open a link such as https://call.element.io/TestElementCall on a recent Android device
2. Observe that the link is opened in the browser

#### What did you expect?

Element X Android open and host the Call.

#### What happened instead?

The link is open in the web browser since https://call.element.io/.well-known/assetlinks.json is not returning expected Json but rather is trying to create a call.

### Operating system

Android

### URL for webapp

https://call.element.io/TestElementCall 

### Will you send logs?

No

**Comment by toger5** [comment]
I expected the desired bahaviour to be:
Link opens in the browser and shows you a bottom sheet with the option to open the app?

This might be sth we removed recently however? Since the usage of links will hopefully transition to matrix.to links and ppl joining with there verified accounts. Only for guest access we will have links (so only for users on on matrix, so they will not have an element app anyways.)

**Comment by bmarty** [comment]
Yes, the system may display a popup to let the user choose an app like below (note, this is the second type of popup and on an old device - API 25):

<img width="311" alt="image" src="https://github.com/user-attachments/assets/fd195de7-249f-47d4-bdcb-e08339a136cd">

But it will not do if the system does not trust Element X to be able to open the link, which is the purpose of https://call.element.io/.well-known/assetlinks.json

EDIT: first type of popup (the first time it is displayed, on API 29):

<img width="297" alt="image" src="https://github.com/user-attachments/assets/0efdc4a1-86bd-4126-baec-743608b761f0">

**Comment by hughns** [comment]
FTR, plan is to change how EC is deployed to reinstate the missing .well-known files.

**Comment by hughns** [comment]
This missing [call.element.io/.well-known/assetlinks.json](https://call.element.io/.well-known/assetlinks.json) asset is now present again.

Can someone with an Android device confirm that `call.element.io` deep links are now working?

**Comment by hughns** [comment]
> I expected the desired bahaviour to be: Link opens in the browser and shows you a bottom sheet with the option to open the app?

For the record: what you have described is not the expected behaviour for call.element.io links.

EX on iOS and Android are configured to be the associated app for opening the call.element.io links. So, unless the user has turned it off (on Android, maybe not on iOS), the call.element.io links should always open in EX directly (not opening the browser first).

call.element.dev does *not* have the app association set up so those links should always open in a browser and then element-call shows a try to launch an app.

**Comment by hughns** [comment]
I've confirmed on an Android handset that the app association is now working again.
