### ISSUE TITLE
Spatial audio breaks AEC in Chrome

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-call#381]
In Chrome, at least: enabling spatial audio on a Macbook Pro meant that everyone else in the call heard bad echo of themselves.

**Comment by fkwp** [comment]
The problem seems to be that Chrome does AEC on the WebRTC RTP tracks and _not_ on Web Audio. This can be solved by adapting Alex Ciarlillo's [loopback hack](https://gist.github.com/alexciarlillo/4b9f75516f93c10d7b39282d10cd17bc). 

More details here: https://github.com/webrtc/samples/issues/1243#issuecomment-1027814331
