### ISSUE TITLE
Video preview on lobby view has mirrored UI elements on Firefox

### ISSUE THREAD

**Issue by dbkr** [vector-im/element-call#392]
**Describe the bug**
The video preview in the lobby view has the 'watch in pip' hover mirrored in firefox (the main view is fine).

**Screenshots**
<img width="1392" alt="Screenshot 2022-06-10 at 13 34 44" src="https://user-images.githubusercontent.com/986903/173090056-c0bc8f44-cbf9-41d8-a199-d886e88f50af.png">

**Comment by ara4n** [comment]
So this turns out to be a bug in firefox.  They explicitly added in the ability to detect when video is horizontally flipped (and then compensate for the controls by setting `flipped="true"` on the shadow DOM videocontrols element in https://github.com/mozilla/gecko-dev/commit/04b688c697485f20b8073b9b8fa5ea2226196673.  However, for some reason, this check isn't kicking in on the preview screen.  It gets it right once you're in video grid mode though.

The check in firefox looks to be something like:

```js
      if (video.getTransformToViewport().a == -1) {
        shadowRoot.firstChild.setAttribute("flipped", true);
      }
```

...so perhaps the transform we're applying doesn't have an `a` component of -1 for the preview?

**Comment by ara4n** [comment]
ah, right, yes, that's what's happening; it has:

```css
transform: scaleX(-1.01);
```

**Comment by ara4n** [comment]
Looks like this was added as a hack for avatar layout in https://github.com/vector-im/element-call/commit/d1368f46220d36e6f76da24e0f08f78951f507de
