### ISSUE TITLE
Add support for calling from multiple devices

### ISSUE THREAD

**Issue by robertlong** [vector-im/element-call#47]
[MSC 3401](https://github.com/matrix-org/matrix-doc/blob/matthew/group-voip/proposals/3401-group-voip.md) specifies a sources array that allows for a single user to join a group call from multiple devices.

**Comment by ara4n** [comment]
the use case here is so that i can handover a call from desktop to mobile and vice versa (something i do constantly on jitsi).  currently it "works" only because all my devices are logged in as different users (matthew-chrome, matthew-ios etc) - whereas it would break if i actually logged in as the same user(!)

**Comment by ptman** [comment]
Google meet has something called companion mode, but doesn't allow taking e.g. video from one and audio from another device
