### ISSUE TITLE
Way to direct call the users (Google duo alternative) 

### ISSUE THREAD

**Issue by AnisTaluqdar** [vector-im/element-call#722]
#### What would you like to do?

I like to call the users directly. 
I know it is possible by using matrix but I wanted to use as call only like google duo alternative. 

#### Why would you like to do it?
Avoiding texting. If someone need they can directly connect via call.

#### How would you like to achieve it?

Having option to call users.

**Comment by toger5** [comment]
Do I understand correctly, that you would like to have the option to type in a username in the standalone version of element call and this user then should get invited to a room/call or is that issue asking for the 1:1 calling in element web to be ported to use the element call app (instead of the legacy call system)? 

In the first case: The receiving user would need to be logged into element call or element web to be notified about the new room/call.
If there is not already a room with the two participating users it is not possible to make element web ring (at least not today)

It could be possible however to make element web and element call ring if an invitation to a room with room type call is received.

**Comment by AnisTaluqdar** [comment]
> It could be possible however to make element web and element call ring if an invitation to a room with room type call is received.

It's enough, But not in element web. My idea is only call not text

**Comment by Thatoo** [comment]
I understand this point.
Would it be possible then to have a way to set mainline Element client to display in a very minimal and simple UI/UX showing only the list of rooms and once a room selected the start or join call button?
