### ISSUE TITLE
EC doesn't recover from switching networks.

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-call#928]
### Steps to reproduce

1. join a call on wifi
2. Plug in a cat5 cable
3. Disable wifi
4. Observe that EC can't reconnect

#### What did you expect?

Resilience to network transitions via ICE.

#### What happened instead?

Call video feeds gets stuck in "...connecting" tiles.

### Operating system

macOS

### Browser information

Version 109.0.5414.119 (Official Build) (arm64)

### URL for webapp

call.element.io

### Will you send logs?

No

**Comment by EnricoSchw** [comment]
I've been working on this bug and I have a solution:

We detect a switch of the network interface by checking the state of ‘iceConnectionState’ switching to ‘disconnected’. If this happens, we are doing an ICE restart. Ice Restart works in any browser and this solution is often recommended on network interface switches and very simple.

But from a user perspective this solution is not quite optimal. An ICE restart can have a delay of up to 15s seconds. In this delay time the video is frozen.

So I looked for better solutions. But all the solutions (Continuous Nomination, Continual Gathering, Backup Pair) I've found which do not require an ICE restart, fail.  The reason is ICE gathering in the browser is a more closed and finished process. (other, not browser implementations are more flexible in this point)

Means: When the WebRTC connection transitions to the 'icconnectionsate' connected state, the gathering process is finished and all not selected ICE candidates are pruned. But a recovery of the existing disconnected WebRTC connection is only possible if additional candidates could be added to the WebRTC connection or not selected candidates would not be pruned. With other words, once ICE has connected (or failed) the ICE agent will ignore new network interfaces.


I could optimiye the process of the ICE Restart in terms of time. I could use `window.navigator.online` to determine the disconnection earlier, etc.. But 'we partially de-trickle candidates by waiting for `delay` before sending them amalgamated, in order to avoid sending too many m.call.candidates events and hitting rate limits in Matrix.' So I optimise on one side and on the other we slow down again.

@dbkr  What do you think?  Do I basically misunderstand here something?

**Comment by BugZappa** [comment]
+1 

It would be nice if Element Call could recover from network changes.
