### ISSUE TITLE
Screen sharing stream doesn't end on Safari the second time

### ISSUE THREAD

**Issue by dbkr** [vector-im/element-call#944]
### Steps to reproduce

1. Join call from safari
2. Join call from another browser
3. Start screen sharing from other browser
4. Stop screenshare
5. Start screensharing from other browser again
6. Stop screensharing

#### What did you expect?
Screensharing session stops everywhere

#### What happened instead?
After stopping the second time, the screenshare just goes black and stays looking like the other browser is still screen sharing.

### Browser information

Safari 16.3

### Will you send logs?

Yes

**Comment by EnricoSchw** [comment]
## Bug and bugfix description

The screen share bug in Safari occurs because we trigger a media renegotiation twice. The new Safari 16.4 ignores the second SDP exchange like Chrome and Firefox. Means this bug is only related to older versions of Safari.

But I still invested time to check what is wrong.  

The bug occurs because we are using the `sender.setStream` method if we reuse a Transceiver.
The method was introduced to make tracks (audio and video) belonging to each other clear to WebRTC:

`https://github.com/w3c/webrtc-pc/issues/1826`

WebRTC saves that two tracks belong to each other in the `msid` attribute of the SDP like this:
```
a=ssrc:632943048 msid: stream-id track-id

```

Two media lines with the same stream id probably belong  than together


## Software design

WebRTC itself only relies on the exchange of tracks and not on the exchange of MediaStreams. The media stream id is only an info for track synchronisation.

### Consequence for Software design:

If we reuse transceivers, then the old transceivers already have a MediaStream. It follows:
1. We have to be careful where we add tracks. Two transceivers with the same MediaStream building Tracks which belongs to each other.
2. The remote client thinks it's the same stream as he get in the history.  In my opinion this is irrelevant, because since Webrtc is based on the exchange of tracks, MediaStream IDs are not real identifiers, just information that tracks belongs together.
