### ISSUE TITLE
Debugging with `git bisect`-like deployment

### ISSUE THREAD

**Issue by notramo** [vector-im/element-call#965]
### Your use case

When Element Call came out, it was great. It had better connectivity than any other Matrix client. It connected quite fast. I recommended it to several people.
Along the way, you are actively messing it up. It is barely usable now. Most of the time, it doesn't connect at all, and says "Connecting...", or it says it's connected, but there is no audio or video.
The latest version is spinning the CPU on 100%, while, of course, there are no audio or video.

I recommend deploying every commit to the storage, and creating a `git bisect`-like interface:
- In the devtools, there should be a button: "Start bisect debugging". This implies that the current version doesn't work.
- The user would select a date where it worked. The app redirects to that version.
- A header would be displayed: "Does it work?" with answers Yes / No.
- The user can try that version out on their own setup. Based on the test results, they click the appropriate button in the header.
- The app redirects to the next bisect commit.
- ...

This feature would enable users to significantly contribute to debugging, while using their own setup, and not having to set up a React development environment.

### Have you considered any alternatives?

Not only considered, but using: Google Meet, and Microsoft Teams. Because those work.

**Comment by robintown** [comment]
Hi, thanks for your suggestion. While this is normally something we would leave open on the chance that someone from the community wants to contribute this, in this case, it would require significant effort from our team to set up such a version archival system. Because this would provide only marginal benefits over bisecting with Git, that is not effort we're willing to invest at this time. Instead, we're focusing on other ways to let users help us out with debugging, such as through telemetry.
